theme: jekyll-theme-hacker
title: <a href="https://openanswer.github.io/yapt/">YAPT</a>
description: Yet Another Python Tutorial <a href="mailto:support@openanswer.io">(support@openanswer.io)</a>

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
